name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CI: true
      BASE_URL: https://www.demoblaze.com
      ARGOS_TOKEN: 'argos_b5e0db181efd7dd7d5cc91f736599e4403'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Option A (quick fix): ignore lockfile mismatches + peer deps
      - name: Install dependencies (legacy peer deps)
        run: npm ci --force

      # If you prefer to keep browsers in the cache across runs, you can add:
      # - uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/ms-playwright
      #     key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --force

      - name: Run Playwright tests
        run: npm run auth-sign-login-chrome

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30